apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: flux-system
spec:
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
      version: 'v1.94.2'
  interval: 168h
  releaseName: tailscale-operator
  targetNamespace: tailscale
  values:
    operatorConfig:
      hostname: oke
      image:
        repository: ghcr.io/tailscale/k8s-operator
    proxyConfig:
      image:
        repository: ghcr.io/tailscale/tailscale
    apiServerProxyConfig:
      mode: "true"
