---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miniflux
  annotations:
    tailscale.com/proxy-group: oke-ingress
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
      - miniflux
  defaultBackend:
    service:
      name: miniflux
      port:
        number: 80

