---
namespace: miniflux
labels:
  - pairs:
      app: miniflux
    includeSelectors: true
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjob_refresh.yaml
  - cronjob_cleanup.yaml
  - cluster.yaml
images:
  - name: miniflux
    newName: ghcr.io/miniflux/miniflux
    newTag: "2.2.19-distroless@sha256:c752402519127b6eb4081bace4bea3ca89465b2c7e3f354b7be020a822e3d8a3"
  - name: miniflux-debug
    newName: ghcr.io/miniflux/miniflux
    newTag: "2.2.19@sha256:8810dfe7f4d9979f9dc1385607695c116f049daa586c635a9a1fb3c58936b074"
configMapGenerator:
  - name: env
    envs:
      - env.sh
patches:
  - target:
      kind: Deployment
      name: miniflux
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: pg-app
                key: fqdn-uri
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: env
replacements:
  - source:
      kind: Deployment
      name: miniflux
      fieldPath: spec.template.spec.containers.0.env
    targets:
      - select:
          kind: Deployment
          labelSelector: app=miniflux
        fieldPaths:
          - spec.template.spec.initContainers.*.env
      - select:
          kind: CronJob
          labelSelector: app=miniflux
        fieldPaths:
          - spec.jobTemplate.spec.template.spec.containers.*.env
  - source:
      kind: Deployment
      name: miniflux
      fieldPath: spec.template.spec.containers.0.envFrom
    targets:
      - select:
          kind: Deployment
          labelSelector: app=miniflux
        fieldPaths:
          - spec.template.spec.initContainers.*.envFrom
      - select:
          kind: CronJob
          labelSelector: app=miniflux
        fieldPaths:
          - spec.jobTemplate.spec.template.spec.containers.*.envFrom
replicas:
  - name: miniflux
    count: 1
