---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg
spec:
  instances: 2
  storage:
    storageClass: longhorn
    size: 1Gi
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5-202507280807-minimal-bookworm
  bootstrap:
    initdb:
      database: miniflux
      owner: miniflux
