---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg
spec:
  instances: 1
  storage:
    storageClass: longhorn
    size: 16Gi
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-minimal-trixie
