---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thelounge
  annotations:
    tailscale.com/proxy-group: oke-ingress
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
      - l
  defaultBackend:
    service:
      name: thelounge
      port:
        number: 80

