---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-s3
spec:
  dataFrom:
  - extract:
      key: cnpg_s3
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci
  target:
    name: cnpg-s3
