---
- name: download alpine
  hosts: localhost
  vars:
    release: "3.22"
    patch: ".0"
    arch: "x86_64"
    provisioner: "cloudinit"
    img_url: "https://dl-cdn.alpinelinux.org/alpine/v{{ release }}/releases/cloud/oci_alpine-{{ release }}{{ patch }}-{{ arch }}-uefi-{{ provisioner }}-r0.qcow2"
    filename: "{{ img_url | urlsplit('path') | basename }}"
  collections:
    - oracle.oci
  tasks:
    - file:
        path: ../tmp/
        state: directory
      register: tmp
    - get_url:
        dest: "{{ tmp.path }}/{{ filename }}"
        url: "{{ img_url }}"
        checksum: "sha512:{{ img_url }}.sha512"
      register: download
    # - stat:
    #     path: "{{ download.dest }}"
    #     checksum_algorithm: md5
    #   register: stat
    - oci_object_storage_object:
        namespace_name: lrejjftxslsd
        bucket_name: images
        object_name: "{{ filename }}"
        src: "{{ download.dest }}"
        force: false

