---
- hosts: server
  vars:
    token:
  collections:
    - kubernetes.core
  tasks:
    - register: tf
      delegate_to: localhost
      tags:
        - test_tf
      no_log: true
      cloud.terraform.terraform_output:
        binary_path: tofu
        project_path: "{{ playbook_dir | dirname }}"
    - package:
        state: latest
        name:
          - k3s
    - register: conf
      copy:
        dest: /etc/conf.d/k3s
        backup: true
        content: |
          export PATH="/usr/libexec/cni/:$PATH"
          K3S_EXEC="server"
          K3S_OPTS="--disable-network-policy --disable-cloud-controller --node-external-ip {{ inventory_hostname }} --node-ip {{ inventory_hostname }} --advertise-address {{ inventory_hostname }} --flannel-iface tailscale0 --disable traefik"
          export K3S_TOKEN='{{ tf.outputs.k3s_token.value }}'
    - register: conf
      copy:
        src: "{{ playbook_dir | dirname }}/manifests/helmchart-external-secrets.yaml"
        dest: /var/lib/rancher/k3s/server/manifests/
    - register: conf
      copy:
        src: "{{ playbook_dir | dirname }}/manifests/clustersecretstore-oci.yaml"
        dest: /var/lib/rancher/k3s/server/manifests/
    - register: conf
      copy:
        src: "{{ playbook_dir | dirname }}/manifests/tailscale-operator.yaml"
        dest: /var/lib/rancher/k3s/server/manifests/
    - service:
        name: k3s
        enabled: true
        state: "{{ conf.changed | ternary('restarted', 'started') }}"
    - wait_for:
        path: /etc/rancher/k3s/k3s.yaml
    - wait_for:
        port: 6443
